name: fourth_pyramid_task
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <3.6.0"


dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.4
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.6
  barcode_scanner: ^4.0.2
  go_router: ^14.2.1
  flutter_zxing: ^1.7.0
  hive: ^2.2.3
  image_picker: ^1.1.2
  path_provider: ^2.1.3
  qr_code_scanner: ^1.0.1
  barcode: ^2.2.8
  barcode_scan2: ^4.3.2
  flutter_svg: ^2.0.10+1
  mobile_scanner: ^6.0.2
  pretty_qr_code: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0


flutter:

  
  uses-material-design: true

  assets:
    - assets/images/
    

 
